### PR TITLE
[G2M] Communications - Journal

### PR DESCRIPTION
**Pull request by woozyking**

### CODE REVIEW

**Comment by woozyking** [comment]
> 
> 
> doing this for everyday going to feel like a chore, can we have a more flexible version that can cover 1~3 days? also it's likely to be hard for some data projects been break up into detailed sub tasks, so we may need to adapt to a version that have a larger task with longer time span.

good point. though the emphasis is more on logging the journal on the last workday, i suppose we can make it something like _last work period_. the planning part is secondary but encouraged to do whenever possible.

**Comment by hyx131** [comment]
instead of the last workday, maybe a journal log per task/issue (the broken down & small versions, not some extensive and large task/issues)? In the mean time still create 'today's' planning and task break down every day(or whenever possible), but give a summary journal log once the task/issue resolved.

**Comment by woozyking** [comment]
> instead of the last workday, maybe a journal log per task/issue (the broken down & small versions, not some extensive and large task/issues)? In the mean time still create 'today's' planning and task break down every day(or whenever possible), but give a summary journal log once the task/issue resolved.

the last workday part (or potentially session) part is so that this setup is to provide a concise summary for your coworkers of what you've been working on. the per-task/issue approach may not work very well.

would the third point under `Potential Improvements` cover the use pattern you described?

**Comment by hyx131** [comment]
> > instead of the last workday, maybe a journal log per task/issue (the broken down & small versions, not some extensive and large task/issues)? In the mean time still create 'today's' planning and task break down every day(or whenever possible), but give a summary journal log once the task/issue resolved.
> 
> the last workday (or potentially session) part is so that this setup is to provide a concise summary for your coworkers of what you've been working on. the per-task/issue approach may not work very well.
> 
> would the third point under `Potential Improvements` cover the use pattern you described?

ahhh i see. 3rd point from `Potential Improvements` and those automations would be great to have! I initially thought a journal would be written in a format different than the tasks (which may be short/concise/may seem random/ jot notes), and so just to clarify it here, logging out previous workday's finished tasks would be sufficient to count as a journal then right? (e.g.they don't have to be in complete sentence format)

**Comment by woozyking** [comment]
> and so just to clarify it here, logging out previous workday's finished tasks would be sufficient to count as a journal then right? (e.g.they don't have to be in complete sentence format)

@hyx131 yes that would be like a good starting point -- similar spirit in how we want to leverage commit messages as release notes. it cannot be 100% representative of the eventual summary, but at least offers a quick 90%. and if you so will, they can be edited into some other formats, just perhaps not a "Dear Diary" one.

**Comment by hyx131** [comment]
> > and so just to clarify it here, logging out previous workday's finished tasks would be sufficient to count as a journal then right? (e.g.they don't have to be in complete sentence format)
> 
> @hyx131 yes that would be like a good starting point -- similar spirit in how we want to leverage commit messages as release notes. it cannot be 100% representative of the eventual summary, but at least offers a quick 90%. and if you so will, they can be edited into some other formats, just perhaps not a "Dear Diary" one.

have to admit, "Dear Diary" is more fun to read tho 😄

**Pull request merged**
